"""table2

Revision ID: 40c466de6d27
Revises: 7fc9ea1de54d
Create Date: 2019-01-09 20:50:25.054780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c466de6d27'
down_revision = '7fc9ea1de54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'user', ['user_id'], ['id'])
    op.drop_column('file', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('author', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'user', ['author'], ['id'])
    op.drop_column('file', 'user_id')
    # ### end Alembic commands ###
