"""test

Revision ID: 4e181d1787bf
Revises: cecf9f03fa5b
Create Date: 2019-01-16 13:34:48.213252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e181d1787bf'
down_revision = 'cecf9f03fa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'otp_secret')
    # ### end Alembic commands ###
