"""new

Revision ID: 6ead91a2f1e7
Revises: 9a6291112bf0
Create Date: 2019-01-20 12:54:10.607546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ead91a2f1e7'
down_revision = '9a6291112bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('activated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'activated')
    # ### end Alembic commands ###
