"""Deuxieme essai

Revision ID: b0b2dbf23198
Revises: 591d9d0c4e95
Create Date: 2019-01-15 18:01:00.973705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b2dbf23198'
down_revision = '591d9d0c4e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'confirmed')
    # ### end Alembic commands ###
